name: ✨ 기능 요청
description: 새로운 기능을 제안하려면 이 템플릿을 사용하세요.
title: "[Feature] "
labels: ["feature", "triage"]
assignees: []

body:
  - type: input
    id: summary
    attributes:
      label: 간단 요약
      placeholder: 예) 상품 목록에 필터 기능 추가
    validations:
      required: true

  - type: textarea
    id: detail
    attributes:
      label: 상세 설명
      placeholder: 어떤 기능이며 왜 필요한지 자세히 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 해야 할 일 (To-do)
      placeholder: |
        - [ ] UI 기획
        - [ ] API 스펙 확정
        - [ ] 프론트 구현
        - [ ] 백엔드 구현
        - [ ] 테스트
    validations:
      required: false
